function showContent1() {
    var circles = document.getElementsByClassName("circulos");
    circles[0].style.backgroundColor = 'red'
    circles[0].style.color = 'white'
    circles[1].style.backgroundColor = 'red'
    circles[1].style.color = 'white'
    circles[2].style.backgroundColor = 'red'
    circles[2].style.color = 'white'
    circles[3].style.backgroundColor = 'red'
    circles[3].style.color = 'white'
    circles[4].style.backgroundColor = 'red'
    circles[4].style.color = 'white'
    circles[5].style.backgroundColor = 'red'
    circles[5].style.color = 'white'
    circles[6].style.backgroundColor = 'red'
    circles[6].style.color = 'white'
    circles[7].style.backgroundColor = 'red'
    circles[7].style.color = 'white'
    circles[8].style.color = 'white'
    circles[8].style.backgroundColor = 'red'
    circles[9].style.color = 'white'
    circles[9].style.backgroundColor = 'red'
    circles[10].style.color = 'white'
    circles[10].style.backgroundColor = 'red'
    circles[11].style.color = 'white'
    circles[11].style.backgroundColor = 'red'

    document.getElementById('content1').style.display = 'flex'
    document.getElementById('content2').style.display = 'none'
    document.getElementById('content3').style.display = 'none'
    document.getElementById('content4').style.display = 'none'
    document.getElementById('content5').style.display = 'none'
    document.getElementById('content6').style.display = 'none'
    document.getElementById('content7').style.display = 'none'
    document.getElementById('content8').style.display = 'none'
    document.getElementById('content9').style.display = 'none'
    document.getElementById('content10').style.display = 'none'
    document.getElementById('content11').style.display = 'none'
    document.getElementById('content12').style.display = 'none'

    document.getElementById('circulo1').style.color = 'white'
    document.getElementById('circulo1').style.backgroundColor = 'grey'
}

function showContent2() {
    var circles = document.getElementsByClassName("circulos");
    circles[0].style.backgroundColor = 'red'
    circles[0].style.color = 'white'
    circles[1].style.backgroundColor = 'red'
    circles[1].style.color = 'white'
    circles[2].style.backgroundColor = 'red'
    circles[2].style.color = 'white'
    circles[3].style.backgroundColor = 'red'
    circles[3].style.color = 'white'
    circles[4].style.backgroundColor = 'red'
    circles[4].style.color = 'white'
    circles[5].style.backgroundColor = 'red'
    circles[5].style.color = 'white'
    circles[6].style.backgroundColor = 'red'
    circles[6].style.color = 'white'
    circles[7].style.backgroundColor = 'red'
    circles[7].style.color = 'white'
    circles[8].style.color = 'white'
    circles[8].style.backgroundColor = 'red'
    circles[9].style.color = 'white'
    circles[9].style.backgroundColor = 'red'
    circles[10].style.color = 'white'
    circles[10].style.backgroundColor = 'red'
    circles[11].style.color = 'white'
    circles[11].style.backgroundColor = 'red'


    document.getElementById('content1').style.display = 'none'
    document.getElementById('content2').style.display = 'flex'
    document.getElementById('content3').style.display = 'none'
    document.getElementById('content4').style.display = 'none'
    document.getElementById('content5').style.display = 'none'
    document.getElementById('content6').style.display = 'none'
    document.getElementById('content7').style.display = 'none'
    document.getElementById('content8').style.display = 'none'
    document.getElementById('content9').style.display = 'none'
    document.getElementById('content10').style.display = 'none'
    document.getElementById('content11').style.display = 'none'
    document.getElementById('content12').style.display = 'none'


    document.getElementById('circulo2').style.color = 'white'
    document.getElementById('circulo2').style.backgroundColor = 'gray'
}

function showContent3() {
    var circles = document.getElementsByClassName("circulos");
    circles[0].style.backgroundColor = 'red'
    circles[0].style.color = 'white'
    circles[1].style.backgroundColor = 'red'
    circles[1].style.color = 'white'
    circles[2].style.backgroundColor = 'red'
    circles[2].style.color = 'white'
    circles[3].style.backgroundColor = 'red'
    circles[3].style.color = 'white'
    circles[4].style.backgroundColor = 'red'
    circles[4].style.color = 'white'
    circles[5].style.backgroundColor = 'red'
    circles[5].style.color = 'white'
    circles[6].style.backgroundColor = 'red'
    circles[6].style.color = 'white'
    circles[7].style.backgroundColor = 'red'
    circles[7].style.color = 'white'
    circles[8].style.color = 'white'
    circles[8].style.backgroundColor = 'red'
    circles[9].style.color = 'white'
    circles[9].style.backgroundColor = 'red'
    circles[10].style.color = 'white'
    circles[10].style.backgroundColor = 'red'
    circles[11].style.color = 'white'
    circles[11].style.backgroundColor = 'red'



    document.getElementById('content1').style.display = 'none'
    document.getElementById('content2').style.display = 'none'
    document.getElementById('content3').style.display = 'flex'
    document.getElementById('content4').style.display = 'none'
    document.getElementById('content5').style.display = 'none'
    document.getElementById('content6').style.display = 'none'
    document.getElementById('content7').style.display = 'none'
    document.getElementById('content8').style.display = 'none'
    document.getElementById('content9').style.display = 'none'
    document.getElementById('content10').style.display = 'none'
    document.getElementById('content11').style.display = 'none'
    document.getElementById('content12').style.display = 'none'


    document.getElementById('circulo3').style.color = 'white'
    document.getElementById('circulo3').style.backgroundColor = 'gray'
}

function showContent4() {
    var circles = document.getElementsByClassName("circulos");
    circles[0].style.backgroundColor = 'red'
    circles[0].style.color = 'white'
    circles[1].style.backgroundColor = 'red'
    circles[1].style.color = 'white'
    circles[2].style.backgroundColor = 'red'
    circles[2].style.color = 'white'
    circles[3].style.backgroundColor = 'red'
    circles[3].style.color = 'white'
    circles[4].style.backgroundColor = 'red'
    circles[4].style.color = 'white'
    circles[5].style.backgroundColor = 'red'
    circles[5].style.color = 'white'
    circles[6].style.backgroundColor = 'red'
    circles[6].style.color = 'white'
    circles[7].style.backgroundColor = 'red'
    circles[7].style.color = 'white'
    circles[8].style.color = 'white'
    circles[8].style.backgroundColor = 'red'
    circles[9].style.color = 'white'
    circles[9].style.backgroundColor = 'red'
    circles[10].style.color = 'white'
    circles[10].style.backgroundColor = 'red'
    circles[11].style.color = 'white'
    circles[11].style.backgroundColor = 'red'


    document.getElementById('content1').style.display = 'none'
    document.getElementById('content2').style.display = 'none'
    document.getElementById('content3').style.display = 'none'
    document.getElementById('content4').style.display = 'flex'
    document.getElementById('content5').style.display = 'none'
    document.getElementById('content6').style.display = 'none'
    document.getElementById('content7').style.display = 'none'
    document.getElementById('content8').style.display = 'none'
    document.getElementById('content9').style.display = 'none'
    document.getElementById('content10').style.display = 'none'
    document.getElementById('content11').style.display = 'none'
    document.getElementById('content12').style.display = 'none'


    document.getElementById('circulo4').style.color = 'white'
    document.getElementById('circulo4').style.backgroundColor = 'gray'
}

function showContent5() {
    var circles = document.getElementsByClassName("circulos");
    circles[0].style.backgroundColor = 'red'
    circles[0].style.color = 'white'
    circles[1].style.backgroundColor = 'red'
    circles[1].style.color = 'white'
    circles[2].style.backgroundColor = 'red'
    circles[2].style.color = 'white'
    circles[3].style.backgroundColor = 'red'
    circles[3].style.color = 'white'
    circles[4].style.backgroundColor = 'red'
    circles[4].style.color = 'white'
    circles[5].style.backgroundColor = 'red'
    circles[5].style.color = 'white'
    circles[6].style.backgroundColor = 'red'
    circles[6].style.color = 'white'
    circles[7].style.backgroundColor = 'red'
    circles[7].style.color = 'white'
    circles[8].style.color = 'white'
    circles[8].style.backgroundColor = 'red'
    circles[9].style.color = 'white'
    circles[9].style.backgroundColor = 'red'
    circles[10].style.color = 'white'
    circles[10].style.backgroundColor = 'red'
    circles[11].style.color = 'white'
    circles[11].style.backgroundColor = 'red'



    document.getElementById('content1').style.display = 'none'
    document.getElementById('content2').style.display = 'none'
    document.getElementById('content3').style.display = 'none'
    document.getElementById('content4').style.display = 'none'
    document.getElementById('content5').style.display = 'flex'
    document.getElementById('content6').style.display = 'none'
    document.getElementById('content7').style.display = 'none'
    document.getElementById('content8').style.display = 'none'
    document.getElementById('content9').style.display = 'none'
    document.getElementById('content10').style.display = 'none'
    document.getElementById('content11').style.display = 'none'
    document.getElementById('content12').style.display = 'none'


    document.getElementById('circulo5').style.color = 'white'
    document.getElementById('circulo5').style.backgroundColor = 'gray'
}

function showContent6() {
    var circles = document.getElementsByClassName("circulos");
    circles[0].style.backgroundColor = 'red'
    circles[0].style.color = 'white'
    circles[1].style.backgroundColor = 'red'
    circles[1].style.color = 'white'
    circles[2].style.backgroundColor = 'red'
    circles[2].style.color = 'white'
    circles[3].style.backgroundColor = 'red'
    circles[3].style.color = 'white'
    circles[4].style.backgroundColor = 'red'
    circles[4].style.color = 'white'
    circles[5].style.backgroundColor = 'red'
    circles[5].style.color = 'white'
    circles[6].style.backgroundColor = 'red'
    circles[6].style.color = 'white'
    circles[7].style.backgroundColor = 'red'
    circles[7].style.color = 'white'
    circles[8].style.color = 'white'
    circles[8].style.backgroundColor = 'red'
    circles[9].style.color = 'white'
    circles[9].style.backgroundColor = 'red'
    circles[10].style.color = 'white'
    circles[10].style.backgroundColor = 'red'
    circles[11].style.color = 'white'
    circles[11].style.backgroundColor = 'red'



    document.getElementById('content1').style.display = 'none'
    document.getElementById('content2').style.display = 'none'
    document.getElementById('content3').style.display = 'none'
    document.getElementById('content4').style.display = 'none'
    document.getElementById('content5').style.display = 'none'
    document.getElementById('content6').style.display = 'flex'
    document.getElementById('content7').style.display = 'none'
    document.getElementById('content8').style.display = 'none'
    document.getElementById('content9').style.display = 'none'
    document.getElementById('content10').style.display = 'none'
    document.getElementById('content11').style.display = 'none'
    document.getElementById('content12').style.display = 'none'


    document.getElementById('circulo6').style.color = 'white'
    document.getElementById('circulo6').style.backgroundColor = 'gray'
}

function showContent7() {
    var circles = document.getElementsByClassName("circulos");
    circles[0].style.backgroundColor = 'red'
    circles[0].style.color = 'white'
    circles[1].style.backgroundColor = 'red'
    circles[1].style.color = 'white'
    circles[2].style.backgroundColor = 'red'
    circles[2].style.color = 'white'
    circles[3].style.backgroundColor = 'red'
    circles[3].style.color = 'white'
    circles[4].style.backgroundColor = 'red'
    circles[4].style.color = 'white'
    circles[5].style.backgroundColor = 'red'
    circles[5].style.color = 'white'
    circles[6].style.backgroundColor = 'red'
    circles[6].style.color = 'white'
    circles[7].style.backgroundColor = 'red'
    circles[7].style.color = 'white'
    circles[8].style.color = 'white'
    circles[8].style.backgroundColor = 'red'
    circles[9].style.color = 'white'
    circles[9].style.backgroundColor = 'red'
    circles[10].style.color = 'white'
    circles[10].style.backgroundColor = 'red'
    circles[11].style.color = 'white'
    circles[11].style.backgroundColor = 'red'



    document.getElementById('content1').style.display = 'none'
    document.getElementById('content2').style.display = 'none'
    document.getElementById('content3').style.display = 'none'
    document.getElementById('content4').style.display = 'none'
    document.getElementById('content5').style.display = 'none'
    document.getElementById('content6').style.display = 'none'
    document.getElementById('content7').style.display = 'flex'
    document.getElementById('content8').style.display = 'none'
    document.getElementById('content9').style.display = 'none'
    document.getElementById('content10').style.display = 'none'
    document.getElementById('content11').style.display = 'none'
    document.getElementById('content12').style.display = 'none'


    document.getElementById('circulo7').style.color = 'white'
    document.getElementById('circulo7').style.backgroundColor = 'gray'
}

function showContent8() {
    var circles = document.getElementsByClassName("circulos");
    circles[0].style.backgroundColor = 'red'
    circles[0].style.color = 'white'
    circles[1].style.backgroundColor = 'red'
    circles[1].style.color = 'white'
    circles[2].style.backgroundColor = 'red'
    circles[2].style.color = 'white'
    circles[3].style.backgroundColor = 'red'
    circles[3].style.color = 'white'
    circles[4].style.backgroundColor = 'red'
    circles[4].style.color = 'white'
    circles[5].style.backgroundColor = 'red'
    circles[5].style.color = 'white'
    circles[6].style.backgroundColor = 'red'
    circles[6].style.color = 'white'
    circles[7].style.backgroundColor = 'red'
    circles[7].style.color = 'white'
    circles[8].style.color = 'white'
    circles[8].style.backgroundColor = 'red'
    circles[9].style.color = 'white'
    circles[9].style.backgroundColor = 'red'
    circles[10].style.color = 'white'
    circles[10].style.backgroundColor = 'red'
    circles[11].style.color = 'white'
    circles[11].style.backgroundColor = 'red'



    document.getElementById('content1').style.display = 'none'
    document.getElementById('content2').style.display = 'none'
    document.getElementById('content3').style.display = 'none'
    document.getElementById('content4').style.display = 'none'
    document.getElementById('content5').style.display = 'none'
    document.getElementById('content6').style.display = 'none'
    document.getElementById('content7').style.display = 'none'
    document.getElementById('content8').style.display = 'flex'
    document.getElementById('content9').style.display = 'none'
    document.getElementById('content10').style.display = 'none'
    document.getElementById('content11').style.display = 'none'
    document.getElementById('content12').style.display = 'none'


    document.getElementById('circulo8').style.color = 'white'
    document.getElementById('circulo8').style.backgroundColor = 'gray'
}

function showContent9() {
    var circles = document.getElementsByClassName("circulos");
    circles[0].style.backgroundColor = 'red'
    circles[0].style.color = 'white'
    circles[1].style.backgroundColor = 'red'
    circles[1].style.color = 'white'
    circles[2].style.backgroundColor = 'red'
    circles[2].style.color = 'white'
    circles[3].style.backgroundColor = 'red'
    circles[3].style.color = 'white'
    circles[4].style.backgroundColor = 'red'
    circles[4].style.color = 'white'
    circles[5].style.backgroundColor = 'red'
    circles[5].style.color = 'white'
    circles[6].style.backgroundColor = 'red'
    circles[6].style.color = 'white'
    circles[7].style.backgroundColor = 'red'
    circles[7].style.color = 'white'
    circles[8].style.color = 'white'
    circles[8].style.backgroundColor = 'red'
    circles[9].style.color = 'white'
    circles[9].style.backgroundColor = 'red'
    circles[10].style.color = 'white'
    circles[10].style.backgroundColor = 'red'
    circles[11].style.color = 'white'
    circles[11].style.backgroundColor = 'red'



    document.getElementById('content1').style.display = 'none'
    document.getElementById('content2').style.display = 'none'
    document.getElementById('content3').style.display = 'none'
    document.getElementById('content4').style.display = 'none'
    document.getElementById('content5').style.display = 'none'
    document.getElementById('content6').style.display = 'none'
    document.getElementById('content7').style.display = 'none'
    document.getElementById('content8').style.display = 'none'
    document.getElementById('content9').style.display = 'flex'
    document.getElementById('content10').style.display = 'none'
    document.getElementById('content11').style.display = 'none'
    document.getElementById('content12').style.display = 'none'


    document.getElementById('circulo9').style.color = 'white'
    document.getElementById('circulo9').style.backgroundColor = 'gray'
}

function showContent10() {
    var circles = document.getElementsByClassName("circulos");
    circles[0].style.backgroundColor = 'red'
    circles[0].style.color = 'white'
    circles[1].style.backgroundColor = 'red'
    circles[1].style.color = 'white'
    circles[2].style.backgroundColor = 'red'
    circles[2].style.color = 'white'
    circles[3].style.backgroundColor = 'red'
    circles[3].style.color = 'white'
    circles[4].style.backgroundColor = 'red'
    circles[4].style.color = 'white'
    circles[5].style.backgroundColor = 'red'
    circles[5].style.color = 'white'
    circles[6].style.backgroundColor = 'red'
    circles[6].style.color = 'white'
    circles[7].style.backgroundColor = 'red'
    circles[7].style.color = 'white'
    circles[8].style.color = 'white'
    circles[8].style.backgroundColor = 'red'
    circles[9].style.color = 'white'
    circles[9].style.backgroundColor = 'red'
    circles[10].style.color = 'white'
    circles[10].style.backgroundColor = 'red'
    circles[11].style.color = 'white'
    circles[11].style.backgroundColor = 'red'



    document.getElementById('content1').style.display = 'none'
    document.getElementById('content2').style.display = 'none'
    document.getElementById('content3').style.display = 'none'
    document.getElementById('content4').style.display = 'none'
    document.getElementById('content5').style.display = 'none'
    document.getElementById('content6').style.display = 'none'
    document.getElementById('content7').style.display = 'none'
    document.getElementById('content8').style.display = 'none'
    document.getElementById('content9').style.display = 'none'
    document.getElementById('content10').style.display = 'flex'
    document.getElementById('content11').style.display = 'none'
    document.getElementById('content12').style.display = 'none'


    document.getElementById('circulo10').style.color = 'white'
    document.getElementById('circulo10').style.backgroundColor = 'gray'
}

function showContent11() {
    var circles = document.getElementsByClassName("circulos");
    circles[0].style.backgroundColor = 'red'
    circles[0].style.color = 'white'
    circles[1].style.backgroundColor = 'red'
    circles[1].style.color = 'white'
    circles[2].style.backgroundColor = 'red'
    circles[2].style.color = 'white'
    circles[3].style.backgroundColor = 'red'
    circles[3].style.color = 'white'
    circles[4].style.backgroundColor = 'red'
    circles[4].style.color = 'white'
    circles[5].style.backgroundColor = 'red'
    circles[5].style.color = 'white'
    circles[6].style.backgroundColor = 'red'
    circles[6].style.color = 'white'
    circles[7].style.backgroundColor = 'red'
    circles[7].style.color = 'white'
    circles[8].style.color = 'white'
    circles[8].style.backgroundColor = 'red'
    circles[9].style.color = 'white'
    circles[9].style.backgroundColor = 'red'
    circles[10].style.color = 'white'
    circles[10].style.backgroundColor = 'red'
    circles[11].style.color = 'white'
    circles[11].style.backgroundColor = 'red'



    document.getElementById('content1').style.display = 'none'
    document.getElementById('content2').style.display = 'none'
    document.getElementById('content3').style.display = 'none'
    document.getElementById('content4').style.display = 'none'
    document.getElementById('content5').style.display = 'none'
    document.getElementById('content6').style.display = 'none'
    document.getElementById('content7').style.display = 'none'
    document.getElementById('content8').style.display = 'none'
    document.getElementById('content9').style.display = 'none'
    document.getElementById('content10').style.display = 'none'
    document.getElementById('content11').style.display = 'flex'
    document.getElementById('content12').style.display = 'none'


    document.getElementById('circulo11').style.color = 'white'
    document.getElementById('circulo11').style.backgroundColor = 'gray'
}

function showContent12() {
    var circles = document.getElementsByClassName("circulos");
    circles[0].style.backgroundColor = 'red'
    circles[0].style.color = 'white'
    circles[1].style.backgroundColor = 'red'
    circles[1].style.color = 'white'
    circles[2].style.backgroundColor = 'red'
    circles[2].style.color = 'white'
    circles[3].style.backgroundColor = 'red'
    circles[3].style.color = 'white'
    circles[4].style.backgroundColor = 'red'
    circles[4].style.color = 'white'
    circles[5].style.backgroundColor = 'red'
    circles[5].style.color = 'white'
    circles[6].style.backgroundColor = 'red'
    circles[6].style.color = 'white'
    circles[7].style.backgroundColor = 'red'
    circles[7].style.color = 'white'
    circles[8].style.color = 'white'
    circles[8].style.backgroundColor = 'red'
    circles[9].style.color = 'white'
    circles[9].style.backgroundColor = 'red'
    circles[10].style.color = 'white'
    circles[10].style.backgroundColor = 'red'
    circles[11].style.color = 'white'
    circles[11].style.backgroundColor = 'red'



    document.getElementById('content1').style.display = 'none'
    document.getElementById('content2').style.display = 'none'
    document.getElementById('content3').style.display = 'none'
    document.getElementById('content4').style.display = 'none'
    document.getElementById('content5').style.display = 'none'
    document.getElementById('content6').style.display = 'none'
    document.getElementById('content7').style.display = 'none'
    document.getElementById('content8').style.display = 'none'
    document.getElementById('content9').style.display = 'none'
    document.getElementById('content10').style.display = 'none'
    document.getElementById('content11').style.display = 'none'
    document.getElementById('content12').style.display = 'flex'


    document.getElementById('circulo12').style.color = 'white'
    document.getElementById('circulo12').style.backgroundColor = 'gray'
}
